apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: chatbot-oct10-pr3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-oct10-pr3 
  name: chatbot-oct10-pr3
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: chatbot-oct10-pr3 
